# Generated by Django 6.0 on 2025-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("prazo", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "A Fazer"),
                            ("DOING", "Em Andamento"),
                            ("DONE", "Concluído"),
                        ],
                        default="TODO",
                        max_length=5,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
